version: "3.9"

services:
  app:
    build: .
    working_dir: /code/app
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    environment:
      DEBUG: 1
    volumes:
      - ./app:/code/app
    ports:
      - 80:80
    restart: on-failure
